name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.6.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies and generate CLI docs
        run: poetry install --with docs --no-interaction --no-root

      - name: Commit and Push CDocumentation Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/index.md
          git commit -m "Update documentation" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and deploy MkDocs
        run: |
          poetry run mkdocs gh-deploy --force
      - name: Clean up
        run: rm -rf .cache